name: 'versed-action'
description: 'A tool for string replacement in automation'
branding:
  icon: arrow-right-circle
  color: blue
inputs:
  config:
    description: 'Location of the versed.yml'
    required: false
    default: './versed.yml'
  dir:
    description: 'Directory where versed should be run'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - run: wget https://github.com/fehlhabers/versed/releases/download/v2.1.0/versed
      working-directory: ${{ inputs.dir }}
      shell: bash
    - run: chmod u+x versed
      working-directory: ${{ inputs.dir }}
      shell: bash
    - run: ./versed -f ${{ inputs.config }}
      working-directory: ${{ inputs.dir }}
      shell: bash
