name: Test action

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-run:
    name: Test action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set versions
      uses: ./
      with:
        dir: test

    - name: Check result
      working-directory: test
      run: cat example.json
